#!/bin/bash
cat <<EOF > /etc/consul/service.hcl
services {
  id   = "emojify-api"
  name = "emojify-api"
  port = 9090

  connect {
    sidecar_service {
      port = 20000

      proxy {
        local_service_address = "127.0.0.1"
        local_service_port = 9090

        upstreams {
            destination_name = "emojify-facebox"                                                                   
            local_bind_port = 8003
        }

        upstreams {
            destination_name = "emojify-cache"                                                                   
            local_bind_port = 8005
        }
      }
    }
  }
}
EOF

cat <<EOF > /etc/consul/statsd.hcl
services {
  name = "statsd-exporter"
  port = 9102

  tags = ["scrape"]

  meta {
    service = "emojify-api"
  }
}
EOF

/usr/local/bin/consul reload

/usr/bin/supervisorctl start envoy