{
 "title": "API",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;\n  <span style=\"font-size: 32px\">svc/emojify-api</span>\n</div>"
  },
  {
   "title": "API requests/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status=\"200\"}[1m])+rate(api_service_cache_called_count{status=\"200\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "API errors/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_service_emojify_called_count{status!=\"200\"}[1m])+rate(api_service_cache_called_count{status!=\"200\"}[1m]))+sum(rate(api_service_error_injected[1m]))"
    }
   ]
  },
  {
   "title": "Envoy Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"upstream_emojify-api_http\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=\"upstream_emojify-api_http\"}[1m]))",
     "legendFormat": "destroy-remote"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_destroy_local{envoy_http_conn_manager_prefix=\"upstream_emojify-api_http\"}[1m]))",
     "legendFormat": "destroy-local"
    }
   ]
  },
  {
   "title": "Envoy Authz",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(envoy_ext_authz_connect_authz_ok{service=\"emojify-api\"}[1m])",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(increase(envoy_ext_authz_connect_authz_error{service=\"emojify-api\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Envoy Inbound Requests (downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"upstream_emojify-api_http\"}[30s])) by (envoy_response_code_class, name)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration /cache GET (2xx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_service_cache_called{status=~\"2.*\"}>0) by (status,quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(api_service_cache_called_sum{status=~\"2.*\"}[30s])) / sum(rate(api_service_cache_called_count{status=~\"2.*\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}