{
 "title": "Ingress",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;\n  <span style=\"font-size: 32px\">svc/emojify-ingress</span>\n</div>"
  },
  {
   "title": "Requests / s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"upstream_emojify-api_http|upstream_emojify-website_http\",service=\"emojify-ingress\", envoy_response_code_class=~\"2|4\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"upstream_emojify-api_http|upstream_emojify-website_http\",service=\"emojify-ingress\", envoy_response_code_class=\"5\"}[60s]))"
    }
   ]
  },
  {
   "title": "Envoy Listener Requests Inbound (Downstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"upstream_emojify-api_http|upstream_emojify-website_http\",service=\"emojify-ingress\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "API Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"emojify-api\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx-"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "retry"
    }
   ]
  },
  {
   "title": "API Requests (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"emojify-api\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"emojify-api\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"emojify-api\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "API Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"emojify-api\"}[30s]))",
     "legendFormat": "global timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=\"emojify-api\"}[30s]))",
     "legendFormat": "per try timeout "
    }
   ]
  },
  {
   "title": "API Outlier Ejections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"emojify-api\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Website Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{service=\"emojify-ingress\",envoy_cluster_name=\"emojify-website\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Website Requests (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"emojify-website\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"emojify-website\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"emojify-website\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}