#!/bin/bash
cat <<EOF > /etc/consul/service.hcl
services {
    id   = "emojify-facebox"
    name = "emojify-facebox"
    port = 9090

    connect {
        sidecar_service {
            port = 20000

            proxy {
                local_service_address = "127.0.0.1"
                local_service_port = 9090

                config {
                  envoy_dogstatsd_url = "udp://127.0.0.1:9125"
                  protocol = "http"
                }
            }
        }
    }                                                                                         
} 
EOF

/usr/local/bin/consul reload

/usr/bin/supervisorctl restart envoy