#!/bin/bash
LINES=$(cat /root/proxy.hcl | wc -l)
if [ $LINES -lt 5 ]; then
    fail-message "The proxy.hcl file does not contain the correct configuration."
    exit 1
fi

exit 0

CONFIG=$(consul config read)