FROM nginx

RUN apt-get update && \
    apt-get install -y bash supervisor curl vim

COPY ingress.conf /etc/supervisor/conf.d/

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/consul
COPY client.hcl /etc/consul/

COPY consul /usr/local/bin/consul
COPY envoy /usr/local/bin/envoy

ENTRYPOINT ["/usr/bin/supervisord"]