FROM nicholasjackson/emojify-website:v0.7.0

RUN apt-get update && \
    apt-get install -y bash supervisor curl vim

COPY website.conf /etc/supervisor/conf.d/

COPY env.js /usr/share/nginx/html/config/env.js

RUN mkdir -p /etc/consul
COPY client.hcl /etc/consul/

COPY consul /usr/local/bin/consul
COPY envoy /usr/local/bin/envoy

ENTRYPOINT ["/usr/bin/supervisord"]