#!/bin/bash
cat <<EOF > /etc/consul/service.hcl
services {
    id   = "emojify-ingress"
    name = "emojify-ingress"
    port = 80

    connect {
        sidecar_service {
            port = 20000

            proxy {
                local_service_address = "127.0.0.1"
                local_service_port = 80

                config {
                    protocol = "http"
                    envoy_statsd_url = "udp://127.0.0.1:9125"
                }

                upstreams {
                    destination_name = "emojify-website"                                                                   
                    local_bind_port = 8000

                    config {
                        protocol = "http"
                    }
                }

                upstreams {
                    destination_name = "emojify-api"                                                                   
                    local_bind_port = 8001

                    config {
                        protocol = "http"
                    }
                }
            }
        }
    }
}

services {
  name = "statsd-exporter"
  port = 9102

  tags = ["scrape"]
}
EOF

/usr/local/bin/consul reload

/usr/bin/supervisorctl start envoy